version: "3"
services:
    frontend:
        
        build: ./frontend/
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend
        networks:
            - webappnetwork
    backend:
        #image: webapp-api
        build: ./backend
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge